title: CyberDuck
email: hessor@appstate.edu
description: >- # this means to ignore newlines until "baseurl:"
 
baseurl: "CyberDuck" # the subpath of your site, e.g. /blog
url: "https://hessorr.github.io/CyberDuck/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings

theme: jekyll-theme-cayman
